### PR TITLE
change veri delems to more generic delemens

### PR DESCRIPTION
**Pull request by odjhey**
data elements veri_* does not exist in my system (s/4h 1709)
modified to more generic
char08
numc04
thraw1
etc

### CODE REVIEW

**Comment by odjhey** [comment]
also, scarr_tab is not in some newer systems, changed to type table of scarr.
veri range tab also not exist, created new struct and ttyp Z*_MOCKUP_VERI_RAN

**Comment by sbcgua** [comment]
Ok to change in general. 

My concern was that it also work in NW75 dev edition. So I picked the types from some very basic package. E.g. I'd check about `dmbtr` - this is a financial data element.

But you didn't change `very_alpha` - does it exist in your system ?! it is the part of the same package as other veri_*.

SVER_TABLE_TYPE_VERI_RANGE: For this I think it would be better just to create range type within the class itself - no need for global one. SVER_TABLE_TYPE_VERI_RANGE is used just for template of the range key so any range would do. I'd say even no need for a type, just define a variable of range type in utils-class_constructor and use instead of SVER_TABLE_TYPE_VERI_RANGE.

**Comment by sbcgua** [comment]
UPD: `dmbtr` is present in dev edition. Surprisingly :) So this point is resolved

**Comment by odjhey** [comment]
The weird thing is, `veri_*` packing is up in the `BC` tree, so all installations have it, just that higher versions does not have some of the `VERI` objects (`DEs`, `DOMs` etc.) 

i have not changed all `veri*` ocurrences, just those not in my latest SAP installation.

I can use current [master](https://github.com/sbcgua/mockup_loader/commit/ff64367d9c40f60f6fad4092013b33c8281c8c03) with no modifications in lower installations.

For `SVER_TABLE_TYPE_VERI_RANGE`, please change so others can just clone and use in the future. I'll see if i can PR today.

Thanks a lot!

**Comment by odjhey** [comment]
Hello, please review PR. I have created `TT_RANGE` to replace `SVER_TABLE_TYPE_VERI_RANGE`. Unit test passed in my system.

Thanks and good day!

**Comment by sbcgua** [comment]
almost. Let's do like this instead of `TT_RANGE` - would look cleaner:

```
  data l_dummy_range type range of char1.
  dy_tab ?= cl_abap_typedescr=>describe_by_data( l_dummy_range ).
```
or tell me, I'll pull and fix.

`very*` - yes, strange indeed. No idea why SAP is changing so old package partially :)

**Comment by sbcgua** [comment]
Merging, thanks !

**Pull request merged**
