### PR TITLE
Added factory method

### PR DESCRIPTION
**Pull request by germanysources**
Added the factory method with format settings from table tvarvc.

### CODE REVIEW

**Comment by sbcgua** [comment]
Looks good in general. Good idea with the separate create. 2 points:
- could you please remove diff at the file start ? Do you commit via abapgit (latest) or via external tool ? Seems like there tool you're using adds UTF8 signature at the beginning. I had to fix it last time. Relevant to all XML files in the PR.
- and please resolve the merge conflict

Otherwise look fine, I'll merge after that

**Comment by germanysources** [comment]
I changed the xml files and tried to resolve the merge conflict. I cannot solve merge conflict, this can be done only by you i think.

**Comment by sbcgua** [comment]
xml files: :+1:

Merge conflict happen if the code is not compatible with current branch state. Well, some features were added since the initial request, sorry for that :) But the conflicts must be solved in branch so by the contributor.

It's easy (usually). I usually use external tool for this e.g. GitKraken (quite a convenient one). But please ensure that the code can be imported and compiled after it.

image

See also e.g.: https://rollout.io/blog/resolve-github-merge-conflicts/

**Comment by germanysources** [comment]
Merge conflicts are resolved.

**Comment by sbcgua** [comment]
Merging, thanks ! 👍

**Comment by sbcgua** [comment]
If you'll have a moment to add the feature to the docs, that would be appreciated as well :) (separate PR)

**Comment by germanysources** [comment]
I added documentation in my fork.  When you want i create a new pull request for it.

**Comment by sbcgua** [comment]
Yes the doc looks OK. A few comments:

- please don't change the versions, leave this to me if you don't mind :)
- the best practice is to create a new branch. So you should catch up your master with mine (ask me if you don't know how to do, briefly: add an upstream remote and merge fast forward my master to yours). Then create a new branch, and adjust the doc there. Btw, I've updated the change log with tvarvc feature so it is just REFERENCE remaining

**Comment by germanysources** [comment]
REFERENCE is updated in branch doc_2.0.1

**Comment by sbcgua** [comment]
look fine, pls PR :)

**Pull request merged**
